// @generated by @astrale/typegraph-codegen — DO NOT EDIT
/* eslint-disable */

import { z } from 'zod'

// ─── Node Interfaces ────────────────────────────────────────

export interface Node {}

export interface Link {}

export interface Identity extends Node {}

// ─── Node Types ─────────────────────────────────────────────

export interface Class extends Node {}

export interface Interface extends Node {}

export interface Operation extends Node {}

// ─── Edge Payloads ──────────────────────────────────────────

export interface HasPermPayload {
  perm: number
}

// ─── Methods ────────────────────────────────────────────────

export type ClassNode = Class & {
  readonly id: string
  readonly __type: 'Class'
}

export type InterfaceNode = Interface & {
  readonly id: string
  readonly __type: 'Interface'
}

export type OperationNode = Operation & {
  readonly id: string
  readonly __type: 'Operation'
}

export interface SchemaNodeTypeMap {
  Class: ClassNode
  Interface: InterfaceNode
  Operation: OperationNode
}

// ─── TypeMap ────────────────────────────────────────────────

// ─── Node Input Types ───────────────────────────────────────

export type ClassInput = Class
export type InterfaceInput = Interface
export type OperationInput = Operation

// ─── TypeMap ────────────────────────────────────────────────

import type { TypeMap } from '@astrale/typegraph'

export interface GeneratedTypeMap extends TypeMap {
  nodes: {
    Class: ClassNode
    Interface: InterfaceNode
    Operation: OperationNode
  }
  edges: {
    has_parent: Record<string, never>
    instance_of: Record<string, never>
    has_link: Record<string, never>
    links_to: Record<string, never>
    implements: Record<string, never>
    extends: Record<string, never>
    method_of: Record<string, never>
    has_perm: HasPermPayload
    excluded_from: Record<string, never>
    constrained_by: Record<string, never>
    extends_with: Record<string, never>
  }
  nodeInputs: {
    Class: ClassInput
    Interface: InterfaceInput
    Operation: OperationInput
  }
}

// ─── Typed Graph Factory ────────────────────────────────────

import { createGraph as _createGraph, type GraphOptions } from '@astrale/typegraph'

export function createTypedGraph(options: Omit<GraphOptions, 'schema'>) {
  return _createGraph<typeof schema, GeneratedTypeMap>(schema, {
    ...options,
    validation: { validators, ...options.validation },
  })
}

// ─── Validators ─────────────────────────────────────────────

export const validators = {
  Class: z.object({}),
  Interface: z.object({}),
  Operation: z.object({}),

  HasPerm: z.object({
    perm: z.number().int(),
  }),
} as const

// ─── Schema ─────────────────────────────────────────────────

export const schema = {
  scalars: ['String', 'Int', 'Float', 'Boolean', 'Timestamp', 'Bitmask', 'ByteString'],

  nodes: {
    Node: {
      abstract: true,
    },
    Link: {
      abstract: true,
    },
    Class: {
      abstract: false,
      implements: ['Node'],
    },
    Interface: {
      abstract: false,
      implements: ['Node'],
    },
    Operation: {
      abstract: false,
      implements: ['Node'],
    },
    Identity: {
      abstract: true,
      implements: ['Node'],
    },
  },

  edges: {
    has_parent: {
      endpoints: {
        child: { types: ['Node'], cardinality: { min: 0, max: 1 } },
        parent: { types: ['Node'] },
      },
      constraints: { no_self: true, acyclic: true },
    },
    instance_of: {
      endpoints: {
        instance: { types: ['Node', 'Link'], cardinality: { min: 1, max: 1 } },
        type: { types: ['Class'] },
      },
    },
    has_link: {
      endpoints: {
        source: { types: ['Node'] },
        link: { types: ['Link'], cardinality: { min: 1, max: 1 } },
      },
    },
    links_to: {
      endpoints: {
        link: { types: ['Link'], cardinality: { min: 1, max: 1 } },
        target: { types: ['Node'] },
      },
    },
    implements: {
      endpoints: {
        class: { types: ['Class'] },
        interface: { types: ['Interface'] },
      },
      constraints: { no_self: true },
    },
    extends: {
      endpoints: {
        child: { types: ['Interface'] },
        parent: { types: ['Interface'] },
      },
      constraints: { no_self: true, acyclic: true },
    },
    method_of: {
      endpoints: {
        operation: { types: ['Operation'], cardinality: { min: 0, max: 1 } },
        owner: { types: ['Class', 'Interface'] },
      },
    },
    has_perm: {
      endpoints: {
        identity: { types: ['Identity'] },
        target: { types: ['Node'] },
      },
      attributes: ['perm'],
    },
    excluded_from: {
      endpoints: {
        subject: { types: ['Identity'] },
        excluded: { types: ['Identity'] },
      },
      constraints: { no_self: true, acyclic: true },
    },
    constrained_by: {
      endpoints: {
        subject: { types: ['Identity'] },
        constraint: { types: ['Identity'] },
      },
      constraints: { no_self: true, acyclic: true },
    },
    extends_with: {
      endpoints: {
        subject: { types: ['Identity'] },
        extension: { types: ['Identity'] },
      },
      constraints: { no_self: true, acyclic: true },
    },
  },
} as const

// ─── Schema Types ───────────────────────────────────────────

export type SchemaNodeType = 'Class' | 'Interface' | 'Operation'
export type SchemaEdgeType =
  | 'has_parent'
  | 'instance_of'
  | 'has_link'
  | 'links_to'
  | 'implements'
  | 'extends'
  | 'method_of'
  | 'has_perm'
  | 'excluded_from'
  | 'constrained_by'
  | 'extends_with'
export type SchemaType = SchemaNodeType | SchemaEdgeType

// ─── Core ───────────────────────────────────────────────────

export interface CoreNodeProps {
  Class: Partial<Class>
  Interface: Partial<Interface>
  Operation: Partial<Operation>
}

export interface CoreEdgeEndpoints {
  has_parent: { child: string; parent: string }
  instance_of: { instance: string; type: string }
  has_link: { source: string; link: string }
  links_to: { link: string; target: string }
  implements: { class: string; interface: string }
  extends: { child: string; parent: string }
  method_of: { operation: string; owner: string }
  has_perm: { identity: string; target: string }
  excluded_from: { subject: string; excluded: string }
  constrained_by: { subject: string; constraint: string }
  extends_with: { subject: string; extension: string }
}

export interface CoreEdgeProps {
  has_perm: Partial<HasPermPayload>
}

export interface CoreNodeDef<T extends SchemaNodeType = SchemaNodeType> {
  readonly __type: T
  readonly props: CoreNodeProps[T]
  readonly children?: Record<string, CoreNodeDef>
}

export interface CoreEdgeDef<T extends SchemaEdgeType = SchemaEdgeType> {
  readonly __type: T
  readonly endpoints: CoreEdgeEndpoints[T]
  readonly props?: T extends keyof CoreEdgeProps ? CoreEdgeProps[T] : never
}

export interface CoreDefinition {
  nodes: Record<string, CoreNodeDef>
  edges?: CoreEdgeDef[]
}

export function node<T extends SchemaNodeType>(type: T, props: CoreNodeProps[T]): CoreNodeDef<T>
export function node<T extends SchemaNodeType, C extends Record<string, CoreNodeDef>>(
  type: T,
  props: CoreNodeProps[T],
  options: { children: C },
): CoreNodeDef<T> & { readonly children: C }
export function node(
  type: string,
  props: Record<string, unknown>,
  options?: { children?: Record<string, CoreNodeDef> },
): CoreNodeDef {
  return {
    __type: type as SchemaNodeType,
    props,
    ...(options?.children ? { children: options.children } : {}),
  }
}

export function edge<T extends SchemaEdgeType>(
  type: T,
  endpoints: CoreEdgeEndpoints[T],
  props?: T extends keyof CoreEdgeProps ? CoreEdgeProps[T] : never,
): CoreEdgeDef<T> {
  return { __type: type, endpoints, ...(props ? { props } : {}) } as CoreEdgeDef<T>
}

export function defineCore<const T extends CoreDefinition>(def: T): T {
  return def
}

type FlattenCoreKeys<T extends Record<string, any>> = {
  [K in keyof T & string]:
    | K
    | (T[K] extends { readonly children: infer C extends Record<string, any> }
        ? FlattenCoreKeys<C>
        : never)
}[keyof T & string]

export type ExtractCoreKeys<T extends CoreDefinition> = FlattenCoreKeys<T['nodes']>

export type Refs<T extends CoreDefinition = CoreDefinition> = Record<
  SchemaType | Extract<ExtractCoreKeys<T>, string>,
  string
>
