// @generated by @astrale/typegraph-codegen — DO NOT EDIT

import { z } from 'zod'

// ─── Node Interfaces ────────────────────────────────────────

export interface Timestamped {
  createdAt: string
  updatedAt?: string | null
}

export interface Identity {}

// ─── Node Types ─────────────────────────────────────────────

export interface User extends Identity, Timestamped {
  email: string
  name: string
}

export interface Team extends Identity, Timestamped {
  name: string
  slug: string
}

export interface Space extends Timestamped {
  name: string
  description?: string | null
}

export interface Document extends Timestamped {
  title: string
  content?: string | null
}

// ─── Edge Payloads ──────────────────────────────────────────

export interface MemberOfPayload {
  role: string
}

// ─── Methods ────────────────────────────────────────────────

export type UserNode = User & {
  readonly id: string
  readonly __type: 'User'
}

export type TeamNode = Team & {
  readonly id: string
  readonly __type: 'Team'
}

export type SpaceNode = Space & {
  readonly id: string
  readonly __type: 'Space'
}

export type DocumentNode = Document & {
  readonly id: string
  readonly __type: 'Document'
}

export interface SchemaNodeTypeMap {
  User: UserNode
  Team: TeamNode
  Space: SpaceNode
  Document: DocumentNode
}

// ─── TypeMap ────────────────────────────────────────────────

// ─── Node Input Types ───────────────────────────────────────

export type UserInput = User
export type TeamInput = Team
export type SpaceInput = Space
export type DocumentInput = Document

// ─── TypeMap ────────────────────────────────────────────────

import type { TypeMap } from '@astrale/typegraph'

export interface GeneratedTypeMap extends TypeMap {
  nodes: {
    User: UserNode
    Team: TeamNode
    Space: SpaceNode
    Document: DocumentNode
  }
  edges: {
    memberOf: MemberOfPayload
    owns: Record<string, never>
    contains: Record<string, never>
  }
  nodeInputs: {
    User: UserInput
    Team: TeamInput
    Space: SpaceInput
    Document: DocumentInput
  }
}

// ─── Typed Graph Factory ────────────────────────────────────

import { createGraph as _createGraph, type GraphOptions } from '@astrale/typegraph'

export type SchemaType = typeof schema

export function createTypedGraph(options: Omit<GraphOptions, 'schema'>) {
  return _createGraph<SchemaType, GeneratedTypeMap>(schema, {
    ...options,
    validation: { validators, ...options.validation },
  })
}

// ─── Validators ─────────────────────────────────────────────

export const validators = {

  User: z.object({
    createdAt: z.string(),
    updatedAt: z.string().nullable().optional(),
    email: z.string(),
    name: z.string(),
  }),
  Team: z.object({
    createdAt: z.string(),
    updatedAt: z.string().nullable().optional(),
    name: z.string(),
    slug: z.string(),
  }),
  Space: z.object({
    createdAt: z.string(),
    updatedAt: z.string().nullable().optional(),
    name: z.string(),
    description: z.string().nullable().optional(),
  }),
  Document: z.object({
    createdAt: z.string(),
    updatedAt: z.string().nullable().optional(),
    title: z.string(),
    content: z.string().nullable().optional(),
  }),

  MemberOf: z.object({
    role: z.string(),
  }),
} as const

// ─── Schema ─────────────────────────────────────────────────

export const schema = {
  scalars: ['String', 'Int', 'Float', 'Boolean', 'Timestamp', 'Bitmask', 'ByteString'],

  nodes: {
    Timestamped: {
      abstract: true,
      attributes: ['createdAt', 'updatedAt'],
    },
    User: {
      abstract: false,
      implements: ['Identity', 'Timestamped'],
      attributes: ['createdAt', 'updatedAt', 'email', 'name'],
    },
    Team: {
      abstract: false,
      implements: ['Identity', 'Timestamped'],
      attributes: ['createdAt', 'updatedAt', 'name', 'slug'],
    },
    Space: {
      abstract: false,
      implements: ['Timestamped'],
      attributes: ['createdAt', 'updatedAt', 'name', 'description'],
    },
    Document: {
      abstract: false,
      implements: ['Timestamped'],
      attributes: ['createdAt', 'updatedAt', 'title', 'content'],
    },
    Identity: {
      abstract: true,
    },
  },

  edges: {
    memberOf: {
      endpoints: {
        user: { types: ['User'] },
        team: { types: ['Team'] },
      },
      attributes: ['role'],
    },
    owns: {
      endpoints: {
        team: { types: ['Team'] },
        space: { types: ['Space'], cardinality: { min: 1, max: 1 } },
      },
    },
    contains: {
      endpoints: {
        space: { types: ['Space'] },
        document: { types: ['Document'] },
      },
    },
  },
} as const

// ─── Schema Types ───────────────────────────────────────────

export type SchemaNodeType = 'User' | 'Team' | 'Space' | 'Document'
export type SchemaEdgeType = 'memberOf' | 'owns' | 'contains'
export type SchemaType = SchemaNodeType | SchemaEdgeType

// ─── Core ───────────────────────────────────────────────────

export interface CoreNodeProps {
  User: Partial<User>
  Team: Partial<Team>
  Space: Partial<Space>
  Document: Partial<Document>
}

export interface CoreEdgeEndpoints {
  memberOf: { user: string; team: string }
  owns: { team: string; space: string }
  contains: { space: string; document: string }
}

export interface CoreEdgeProps {
  memberOf: Partial<MemberOfPayload>
}

export interface CoreNodeDef<T extends SchemaNodeType = SchemaNodeType> {
  readonly __type: T
  readonly props: CoreNodeProps[T]
  readonly children?: Record<string, CoreNodeDef>
}

export interface CoreEdgeDef<T extends SchemaEdgeType = SchemaEdgeType> {
  readonly __type: T
  readonly endpoints: CoreEdgeEndpoints[T]
  readonly props?: T extends keyof CoreEdgeProps ? CoreEdgeProps[T] : never
}

export interface CoreDefinition {
  nodes: Record<string, CoreNodeDef>
  edges?: CoreEdgeDef[]
}

export function node<T extends SchemaNodeType>(
  type: T,
  props: CoreNodeProps[T],
): CoreNodeDef<T>
export function node<T extends SchemaNodeType, C extends Record<string, CoreNodeDef>>(
  type: T,
  props: CoreNodeProps[T],
  options: { children: C },
): CoreNodeDef<T> & { readonly children: C }
export function node(
  type: string,
  props: Record<string, unknown>,
  options?: { children?: Record<string, CoreNodeDef> },
): CoreNodeDef {
  return { __type: type as SchemaNodeType, props, ...(options?.children ? { children: options.children } : {}) }
}

export function edge<T extends SchemaEdgeType>(
  type: T,
  endpoints: CoreEdgeEndpoints[T],
  props?: T extends keyof CoreEdgeProps ? CoreEdgeProps[T] : never,
): CoreEdgeDef<T> {
  return { __type: type, endpoints, ...(props ? { props } : {}) } as CoreEdgeDef<T>
}

export function defineCore<const T extends CoreDefinition>(def: T): T {
  return def
}

type FlattenCoreKeys<T extends Record<string, any>> =
  { [K in keyof T & string]: K | (T[K] extends { readonly children: infer C extends Record<string, any> } ? FlattenCoreKeys<C> : never) }[keyof T & string]

export type ExtractCoreKeys<T extends CoreDefinition> = FlattenCoreKeys<T['nodes']>

export type Refs<T extends CoreDefinition = CoreDefinition> =
  Record<SchemaType | Extract<ExtractCoreKeys<T>, string>, string>