export function pascalCase(s: string): string {
  return s
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

export function camelCase(s: string): string {
  const pascal = pascalCase(s)
  return pascal.charAt(0).toLowerCase() + pascal.slice(1)
}

export function section(title: string): string {
  return `// ─── ${title} ${'─'.repeat(Math.max(0, 55 - title.length))}`
}

export function banner(): string {
  return '// @generated by @astrale/typegraph-codegen — DO NOT EDIT'
}
