// @generated by @astrale/typegraph-codegen — DO NOT EDIT
/* eslint-disable */

import { z } from 'zod'
import { op } from '@astrale-os/kernel-api'
import { createMethodFactory, type OperationSelf } from '@astrale-os/kernel-runtime'

// ─── Enums ──────────────────────────────────────────────────

export const CurrencyValues = ['USD', 'EUR', 'GBP', 'JPY'] as const
export type Currency = (typeof CurrencyValues)[number]

export const OrderStatusValues = ['pending', 'confirmed', 'shipped', 'delivered', 'cancelled'] as const
export type OrderStatus = (typeof OrderStatusValues)[number]

// ─── Branded IDs ────────────────────────────────────────────

type NodeBrand = { readonly __nodeId: true }

export type NodeId = string & NodeBrand
export type CustomerId = NodeId & { readonly __customerId: true }
export type ProductId = NodeId & { readonly __productId: true }
export type CategoryId = NodeId & { readonly __categoryId: true }
export type OrderId = NodeId & { readonly __orderId: true }
export type ReviewId = NodeId & { readonly __reviewId: true }

export const NodeId = (id: string) => id as NodeId
export const CustomerId = (id: string) => id as CustomerId
export const ProductId = (id: string) => id as ProductId
export const CategoryId = (id: string) => id as CategoryId
export const OrderId = (id: string) => id as OrderId
export const ReviewId = (id: string) => id as ReviewId

// ─── Type Aliases ───────────────────────────────────────────
export type SKU = string
/** String with format: email */
export type Email = string
/** String with format: url */
export type Url = string

// ─── Node Interfaces ────────────────────────────────────────

export interface Timestamped {
  createdAt: string
  updatedAt?: string | null
}

export interface HasSlug {
  slug: string
}

export interface Priceable {
  priceCents: number
  currency: Currency
}

export interface Identity {}

// ─── Node Types ─────────────────────────────────────────────

export interface Customer extends Identity, Timestamped {
  email: Email
  name: string
  phone?: string | null
}

export interface Product extends Timestamped, HasSlug, Priceable {
  title: string
  description?: string | null
  sku: SKU
  inStock: boolean
  imageUrl?: Url | null
}

export interface Category extends HasSlug {
  name: string
}

export interface Order extends Timestamped {
  status: OrderStatus
  totalCents: number
  notes?: string | null
}

export interface Review extends Timestamped {
  rating: number
  body?: string | null
}

// ─── Edge Payloads ──────────────────────────────────────────

export interface OrderItemPayload {
  quantity: number
  unitPriceCents: number
}

export interface ReviewedPayload {
  rating: number
  body?: string | null
  verified: boolean
}

// ─── Methods ────────────────────────────────────────────────

export interface CustomerMethods {
  displayName(): string | Promise<string>
  recentOrders(args?: { limit?: number }): Order[] | Promise<Order[]>
}

export interface OrderMethods {
  cancel(): boolean | Promise<boolean>
}

export interface OrderItemMethods {
  subtotal(): number | Promise<number>
}

export type CustomerNode = Customer & {
  readonly id: CustomerId
  readonly __type: 'Customer'
} & CustomerMethods

export type ProductNode = Product & {
  readonly id: ProductId
  readonly __type: 'Product'
}

export type CategoryNode = Category & {
  readonly id: CategoryId
  readonly __type: 'Category'
}

export type OrderNode = Order & {
  readonly id: OrderId
  readonly __type: 'Order'
} & OrderMethods

export type ReviewNode = Review & {
  readonly id: ReviewId
  readonly __type: 'Review'
}

export interface SchemaNodeTypeMap {
  Customer: CustomerNode
  Product: ProductNode
  Category: CategoryNode
  Order: OrderNode
  Review: ReviewNode
}

// ─── TypeMap ────────────────────────────────────────────────

export type CustomerInput = Customer
export type ProductInput = Product
export type CategoryInput = Category
export type OrderInput = Order
export type ReviewInput = Review

import type { TypeMap } from '@astrale/typegraph'

export interface GeneratedTypeMap extends TypeMap {
  nodes: {
    Customer: CustomerNode
    Product: ProductNode
    Category: CategoryNode
    Order: OrderNode
    Review: ReviewNode
  }
  edges: {
    placedOrder: Record<string, never>
    orderItem: OrderItemPayload
    inCategory: Record<string, never>
    parentCategory: Record<string, never>
    reviewed: ReviewedPayload
    wishlisted: Record<string, never>
  }
  nodeInputs: {
    Customer: CustomerInput
    Product: ProductInput
    Category: CategoryInput
    Order: OrderInput
    Review: ReviewInput
  }
}

import { createGraph as _createGraph, type GraphOptions } from '@astrale/typegraph'

export function createTypedGraph(options: Omit<GraphOptions, 'schema'>) {
  return _createGraph<typeof schema, GeneratedTypeMap>(schema, {
    ...options,
    validation: { validators, ...options.validation },
  })
}

// ─── Validators ─────────────────────────────────────────────

export const validators = {
  Currency: z.enum(CurrencyValues),
  OrderStatus: z.enum(OrderStatusValues),
  SKU: z.string().min(3).max(20),
  Email: z.string().email(),
  Url: z.string().url(),

  Customer: z.object({
    createdAt: z.string(),
    updatedAt: z.string().nullable().optional(),
    email: z.string().email(),
    name: z.string(),
    phone: z.string().nullable().optional(),
  }),
  Product: z.object({
    createdAt: z.string(),
    updatedAt: z.string().nullable().optional(),
    slug: z.string(),
    priceCents: z.number().int(),
    currency: z.enum(CurrencyValues).default('USD'),
    title: z.string(),
    description: z.string().nullable().optional(),
    sku: z.string().min(3).max(20),
    inStock: z.boolean().default(true),
    imageUrl: z.string().url().nullable().optional(),
  }),
  Category: z.object({
    slug: z.string(),
    name: z.string(),
  }),
  Order: z.object({
    createdAt: z.string(),
    updatedAt: z.string().nullable().optional(),
    status: z.enum(OrderStatusValues).default('pending'),
    totalCents: z.number().int(),
    notes: z.string().nullable().optional(),
  }),
  Review: z.object({
    createdAt: z.string(),
    updatedAt: z.string().nullable().optional(),
    rating: z.number().int(),
    body: z.string().nullable().optional(),
  }),

  OrderItem: z.object({
    quantity: z.number().int().default(1),
    unitPriceCents: z.number().int(),
  }),
  Reviewed: z.object({
    rating: z.number().int(),
    body: z.string().nullable().optional(),
    verified: z.boolean().default(false),
  }),
} as const

// ─── Method Operations ──────────────────────────────────────

export const CustomerOps = {
  displayName: op('Customer.displayName', 'public', z.object({}), z.string()),
  recentOrders: op('Customer.recentOrders', 'private', z.object({ limit: z.number().int().default(10) }), z.array(validators.Order)),
} as const

export const OrderOps = {
  cancel: op('Order.cancel', 'private', z.object({}), z.boolean()),
} as const

export const OrderItemOps = {
  subtotal: op('orderItem.subtotal', 'private', z.object({}), z.number().int()),
} as const

// ─── Schema ─────────────────────────────────────────────────

export const schema = {
  scalars: ['String', 'Int', 'Float', 'Boolean', 'Timestamp', 'Bitmask', 'ByteString'],

  nodes: {
    Timestamped: {
      abstract: true,
      attributes: ['createdAt', 'updatedAt'],
    },
    HasSlug: {
      abstract: true,
      attributes: ['slug'],
    },
    Priceable: {
      abstract: true,
      attributes: ['priceCents', 'currency'],
    },
    Customer: {
      abstract: false,
      implements: ['Identity', 'Timestamped'],
      attributes: ['createdAt', 'updatedAt', 'email', 'name', 'phone'],
    },
    Product: {
      abstract: false,
      implements: ['Timestamped', 'HasSlug', 'Priceable'],
      attributes: ['createdAt', 'updatedAt', 'slug', 'priceCents', 'currency', 'title', 'description', 'sku', 'inStock', 'imageUrl'],
    },
    Category: {
      abstract: false,
      implements: ['HasSlug'],
      attributes: ['slug', 'name'],
    },
    Order: {
      abstract: false,
      implements: ['Timestamped'],
      attributes: ['createdAt', 'updatedAt', 'status', 'totalCents', 'notes'],
    },
    Review: {
      abstract: false,
      implements: ['Timestamped'],
      attributes: ['createdAt', 'updatedAt', 'rating', 'body'],
    },
    Identity: {
      abstract: true,
    },
  },

  edges: {
    placedOrder: {
      endpoints: {
        customer: { types: ['Customer'] },
        order: { types: ['Order'], cardinality: { min: 1, max: 1 } },
      },
      constraints: { unique: true },
    },
    orderItem: {
      endpoints: {
        order: { types: ['Order'] },
        product: { types: ['Product'] },
      },
      attributes: ['quantity', 'unitPriceCents'],
    },
    inCategory: {
      endpoints: {
        product: { types: ['Product'] },
        category: { types: ['Category'] },
      },
    },
    parentCategory: {
      endpoints: {
        child: { types: ['Category'], cardinality: { min: 0, max: 1 } },
        parent: { types: ['Category'] },
      },
      constraints: { no_self: true, acyclic: true },
    },
    reviewed: {
      endpoints: {
        reviewer: { types: ['Customer'] },
        product: { types: ['Product'] },
      },
      constraints: { unique: true },
      attributes: ['rating', 'body', 'verified'],
    },
    wishlisted: {
      endpoints: {
        customer: { types: ['Customer'] },
        product: { types: ['Product'] },
      },
      constraints: { unique: true },
    },
  },

  methods: {
    Customer: {
      displayName: { params: {}, returns: 'String' },
      recentOrders: { params: { limit: { type: 'Int', default: 10 } }, returns: 'Order[]' },
    },
    Order: {
      cancel: { params: {}, returns: 'Boolean' },
    },
    orderItem: {
      subtotal: { params: {}, returns: 'Int' },
    },
  },
} as const

// ─── Bootstrap ──────────────────────────────────────────────

/** Bootstrap manifest — what class/interface nodes to create. */
export const schemaBootstrap = {
  classes: [
    { key: 'Customer', type: 'node' as const },
    { key: 'Product', type: 'node' as const },
    { key: 'Category', type: 'node' as const },
    { key: 'Order', type: 'node' as const },
    { key: 'Review', type: 'node' as const },
    { key: 'orderItem', type: 'link' as const },
    { key: 'reviewed', type: 'link' as const },
  ],
  interfaces: [
    { key: 'Timestamped' },
    { key: 'HasSlug' },
    { key: 'Priceable' },
    { key: 'Identity' },
  ],
  implements: [
    { classKey: 'Customer', interfaceKey: 'Identity' },
    { classKey: 'Customer', interfaceKey: 'Timestamped' },
    { classKey: 'Product', interfaceKey: 'Timestamped' },
    { classKey: 'Product', interfaceKey: 'HasSlug' },
    { classKey: 'Product', interfaceKey: 'Priceable' },
    { classKey: 'Category', interfaceKey: 'HasSlug' },
    { classKey: 'Order', interfaceKey: 'Timestamped' },
    { classKey: 'Review', interfaceKey: 'Timestamped' },
  ],
  extends: [
  ],
} as const

// ─── Method Factory ─────────────────────────────────────────

export const defineMethods = createMethodFactory<typeof schema, GeneratedTypeMap>()

export const defineCustomerMethods = defineMethods.withSelf<CustomerNode>()
export const defineOrderMethods = defineMethods.withSelf<OrderNode>()
export const defineOrderItemMethods = defineMethods.withSelf<OrderItemPayload & OperationSelf>()

// ─── Schema Types ───────────────────────────────────────────

export type SchemaNodeType = 'Customer' | 'Product' | 'Category' | 'Order' | 'Review'
export type SchemaEdgeType = 'placedOrder' | 'orderItem' | 'inCategory' | 'parentCategory' | 'reviewed' | 'wishlisted'
export type SchemaType = SchemaNodeType | SchemaEdgeType

// ─── Core ───────────────────────────────────────────────────

export interface CoreNodeProps {
  Customer: Partial<Customer>
  Product: Partial<Product>
  Category: Partial<Category>
  Order: Partial<Order>
  Review: Partial<Review>
}

export interface CoreEdgeEndpoints {
  placedOrder: { customer: string; order: string }
  orderItem: { order: string; product: string }
  inCategory: { product: string; category: string }
  parentCategory: { child: string; parent: string }
  reviewed: { reviewer: string; product: string }
  wishlisted: { customer: string; product: string }
}

export interface CoreEdgeProps {
  orderItem: Partial<OrderItemPayload>
  reviewed: Partial<ReviewedPayload>
}

export interface CoreNodeDef<T extends SchemaNodeType = SchemaNodeType> {
  readonly __type: T
  readonly props: CoreNodeProps[T]
  readonly children?: Record<string, CoreNodeDef>
}

export interface CoreEdgeDef<T extends SchemaEdgeType = SchemaEdgeType> {
  readonly __type: T
  readonly endpoints: CoreEdgeEndpoints[T]
  readonly props?: T extends keyof CoreEdgeProps ? CoreEdgeProps[T] : never
}

export interface CoreDefinition {
  nodes: Record<string, CoreNodeDef>
  edges?: CoreEdgeDef[]
}

export function node<T extends SchemaNodeType>(
  type: T,
  props: CoreNodeProps[T],
): CoreNodeDef<T>
export function node<T extends SchemaNodeType, C extends Record<string, CoreNodeDef>>(
  type: T,
  props: CoreNodeProps[T],
  children: C,
): CoreNodeDef<T> & { readonly children: C }
export function node(
  type: string,
  props: Record<string, unknown>,
  children?: Record<string, CoreNodeDef>,
): CoreNodeDef {
  return { __type: type as SchemaNodeType, props, ...(children ? { children } : {}) }
}

export function edge<T extends SchemaEdgeType>(
  type: T,
  endpoints: CoreEdgeEndpoints[T],
  props?: T extends keyof CoreEdgeProps ? CoreEdgeProps[T] : never,
): CoreEdgeDef<T> {
  return { __type: type, endpoints, ...(props ? { props } : {}) } as CoreEdgeDef<T>
}

export function defineCore<const T extends CoreDefinition>(def: T): T {
  return def
}

type FlattenCoreKeys<T extends Record<string, any>> =
  { [K in keyof T & string]: K | (T[K] extends { readonly children: infer C extends Record<string, any> } ? FlattenCoreKeys<C> : never) }[keyof T & string]

export type ExtractCoreKeys<T extends CoreDefinition> = FlattenCoreKeys<T['nodes']>

export type Refs<T extends CoreDefinition = CoreDefinition> =
  Record<SchemaType | Extract<ExtractCoreKeys<T>, string>, NodeId>

/** Nested core refs type - supports hierarchical access like core.electronics.phones */
type NestedCoreKeys<T extends Record<string, any>> = {
  [K in keyof T & string]: T[K] extends { readonly children: infer C extends Record<string, any> }
    ? NestedCoreKeys<C> & NodeId  // Parent with children
    : NodeId                       // Leaf node ID
}

export type CoreRefs<T extends CoreDefinition = CoreDefinition> =
  NestedCoreKeys<T['nodes']> & Record<SchemaType, NodeId>
