// @generated by @astrale/typegraph-codegen — DO NOT EDIT

import { z } from 'zod'

// ─── Node Interfaces ────────────────────────────────────────

export interface Timestamped {
  createdAt: string
}

export interface Identity {}

// ─── Node Types ─────────────────────────────────────────────

export interface User extends Identity, Timestamped {
  username: string
  bio?: string | null
}

export interface Post extends Timestamped {
  body: string
}

// ─── Edge Payloads ──────────────────────────────────────────

export interface FollowsPayload {
  since: string
}

// ─── Methods ────────────────────────────────────────────────

export interface UserMethods {
  followerCount(): number | Promise<number>
  isFollowing(args: { other: User }): boolean | Promise<boolean>
}

export interface PostMethods {
  likeCount(): number | Promise<number>
}

export type UserNode = User & {
  readonly id: string
  readonly __type: 'User'
} & UserMethods

export type PostNode = Post & {
  readonly id: string
  readonly __type: 'Post'
} & PostMethods

export interface SchemaNodeTypeMap {
  User: UserNode
  Post: PostNode
}

// ─── TypeMap ────────────────────────────────────────────────

// ─── Node Input Types ───────────────────────────────────────

export type UserInput = User
export type PostInput = Post

// ─── TypeMap ────────────────────────────────────────────────

import type { TypeMap } from '@astrale/typegraph'

export interface GeneratedTypeMap extends TypeMap {
  nodes: {
    User: UserNode
    Post: PostNode
  }
  edges: {
    follows: FollowsPayload
    liked: Record<string, never>
    authored: Record<string, never>
  }
  nodeInputs: {
    User: UserInput
    Post: PostInput
  }
}

// ─── Typed Graph Factory ────────────────────────────────────

import { createGraph as _createGraph, type GraphOptions } from '@astrale/typegraph'

export type SchemaType = typeof schema

export function createTypedGraph(options: Omit<GraphOptions, 'schema'>) {
  return _createGraph<SchemaType, GeneratedTypeMap>(schema, {
    ...options,
    validation: { validators, ...options.validation },
  })
}

// ─── Validators ─────────────────────────────────────────────

export const validators = {

  User: z.object({
    createdAt: z.string(),
    username: z.string(),
    bio: z.string().nullable().optional(),
  }),
  Post: z.object({
    createdAt: z.string(),
    body: z.string(),
  }),

  Follows: z.object({
    since: z.string(),
  }),
} as const

// ─── Schema ─────────────────────────────────────────────────

export const schema = {
  scalars: ['String', 'Int', 'Float', 'Boolean', 'Timestamp', 'Bitmask', 'ByteString'],

  nodes: {
    Timestamped: {
      abstract: true,
      attributes: ['createdAt'],
    },
    User: {
      abstract: false,
      implements: ['Identity', 'Timestamped'],
      attributes: ['createdAt', 'username', 'bio'],
    },
    Post: {
      abstract: false,
      implements: ['Timestamped'],
      attributes: ['createdAt', 'body'],
    },
    Identity: {
      abstract: true,
    },
  },

  edges: {
    follows: {
      endpoints: {
        follower: { types: ['User'] },
        followed: { types: ['User'] },
      },
      constraints: { no_self: true, unique: true },
      attributes: ['since'],
    },
    liked: {
      endpoints: {
        user: { types: ['User'] },
        post: { types: ['Post'] },
      },
      constraints: { unique: true },
    },
    authored: {
      endpoints: {
        author: { types: ['User'] },
        post: { types: ['Post'], cardinality: { min: 1, max: 1 } },
      },
    },
  },

  methods: {
    User: {
      followerCount: { params: {}, returns: 'Int' },
      isFollowing: { params: { other: { type: 'User' } }, returns: 'Boolean' },
    },
    Post: {
      likeCount: { params: {}, returns: 'Int' },
    },
  },
} as const

// ─── Schema Types ───────────────────────────────────────────

export type SchemaNodeType = 'User' | 'Post'
export type SchemaEdgeType = 'follows' | 'liked' | 'authored'
export type SchemaType = SchemaNodeType | SchemaEdgeType

// ─── Core ───────────────────────────────────────────────────

export interface CoreNodeProps {
  User: Partial<User>
  Post: Partial<Post>
}

export interface CoreEdgeEndpoints {
  follows: { follower: string; followed: string }
  liked: { user: string; post: string }
  authored: { author: string; post: string }
}

export interface CoreEdgeProps {
  follows: Partial<FollowsPayload>
}

export interface CoreNodeDef<T extends SchemaNodeType = SchemaNodeType> {
  readonly __type: T
  readonly props: CoreNodeProps[T]
  readonly children?: Record<string, CoreNodeDef>
}

export interface CoreEdgeDef<T extends SchemaEdgeType = SchemaEdgeType> {
  readonly __type: T
  readonly endpoints: CoreEdgeEndpoints[T]
  readonly props?: T extends keyof CoreEdgeProps ? CoreEdgeProps[T] : never
}

export interface CoreDefinition {
  nodes: Record<string, CoreNodeDef>
  edges?: CoreEdgeDef[]
}

export function node<T extends SchemaNodeType>(
  type: T,
  props: CoreNodeProps[T],
): CoreNodeDef<T>
export function node<T extends SchemaNodeType, C extends Record<string, CoreNodeDef>>(
  type: T,
  props: CoreNodeProps[T],
  options: { children: C },
): CoreNodeDef<T> & { readonly children: C }
export function node(
  type: string,
  props: Record<string, unknown>,
  options?: { children?: Record<string, CoreNodeDef> },
): CoreNodeDef {
  return { __type: type as SchemaNodeType, props, ...(options?.children ? { children: options.children } : {}) }
}

export function edge<T extends SchemaEdgeType>(
  type: T,
  endpoints: CoreEdgeEndpoints[T],
  props?: T extends keyof CoreEdgeProps ? CoreEdgeProps[T] : never,
): CoreEdgeDef<T> {
  return { __type: type, endpoints, ...(props ? { props } : {}) } as CoreEdgeDef<T>
}

export function defineCore<const T extends CoreDefinition>(def: T): T {
  return def
}

type FlattenCoreKeys<T extends Record<string, any>> =
  { [K in keyof T & string]: K | (T[K] extends { readonly children: infer C extends Record<string, any> } ? FlattenCoreKeys<C> : never) }[keyof T & string]

export type ExtractCoreKeys<T extends CoreDefinition> = FlattenCoreKeys<T['nodes']>

export type Refs<T extends CoreDefinition = CoreDefinition> =
  Record<SchemaType | Extract<ExtractCoreKeys<T>, string>, string>