// @generated by @astrale/typegraph-codegen — DO NOT EDIT
/* eslint-disable */

import { z } from 'zod'
import { op } from '@astrale-os/kernel-api'
import { createMethodFactory } from '@astrale-os/kernel-runtime'

// ─── Branded IDs ────────────────────────────────────────────

type NodeBrand = { readonly __nodeId: true }

export type NodeId = string & NodeBrand
export type UserId = NodeId & { readonly __userId: true }
export type PostId = NodeId & { readonly __postId: true }

export const NodeId = (id: string) => id as NodeId
export const UserId = (id: string) => id as UserId
export const PostId = (id: string) => id as PostId

// ─── Node Interfaces ────────────────────────────────────────

export interface Timestamped {
  createdAt: string
}

export interface Identity {}

// ─── Node Types ─────────────────────────────────────────────

export interface User extends Identity, Timestamped {
  username: string
  bio?: string | null
}

export interface Post extends Timestamped {
  body: string
}

// ─── Edge Payloads ──────────────────────────────────────────

export interface FollowsPayload {
  since: string
}

// ─── Methods ────────────────────────────────────────────────

export interface UserMethods {
  followerCount(): number | Promise<number>
  isFollowing(args: { other: UserId }): boolean | Promise<boolean>
}

export interface PostMethods {
  likeCount(): number | Promise<number>
}

export type UserNode = User & {
  readonly id: UserId
  readonly __type: 'User'
} & UserMethods

export type PostNode = Post & {
  readonly id: PostId
  readonly __type: 'Post'
} & PostMethods

export interface SchemaNodeTypeMap {
  User: UserNode
  Post: PostNode
}

// ─── TypeMap ────────────────────────────────────────────────

export type UserInput = User
export type PostInput = Post

import type { TypeMap, Graph } from '@astrale/typegraph'

export interface GeneratedTypeMap extends TypeMap {
  nodes: {
    User: UserNode
    Post: PostNode
  }
  edges: {
    follows: FollowsPayload
    liked: Record<string, never>
    authored: Record<string, never>
  }
  nodeInputs: {
    User: UserInput
    Post: PostInput
  }
}

import { createGraph as _createGraph, type GraphOptions } from '@astrale/typegraph'

export function createTypedGraph(options: Omit<GraphOptions, 'schema'>) {
  return _createGraph<typeof schema, GeneratedTypeMap>(schema, {
    ...options,
    validation: { validators, ...options.validation },
  })
}

export type SchemaGraph = Graph<typeof schema, GeneratedTypeMap>

// ─── Validators ─────────────────────────────────────────────

export const validators = {

  User: z.object({
    createdAt: z.string(),
    username: z.string(),
    bio: z.string().nullable().optional(),
  }),
  Post: z.object({
    createdAt: z.string(),
    body: z.string(),
  }),

  Follows: z.object({
    since: z.string(),
  }),
} as const

// ─── Method Operations ──────────────────────────────────────

export const UserOps = {
  followerCount: op('User.followerCount', 'public', z.object({}), z.number().int()),
  isFollowing: op('User.isFollowing', 'public', z.object({ other: z.string() }), z.boolean()),
} as const

export const PostOps = {
  likeCount: op('Post.likeCount', 'public', z.object({}), z.number().int()),
} as const

// ─── Schema ─────────────────────────────────────────────────

export const schema = {
  scalars: ['String', 'Int', 'Float', 'Boolean', 'Timestamp', 'Bitmask', 'ByteString'],

  nodes: {
    Timestamped: {
      abstract: true,
      attributes: ['createdAt'],
    },
    User: {
      abstract: false,
      implements: ['Identity', 'Timestamped'],
      attributes: ['createdAt', 'username', 'bio'],
    },
    Post: {
      abstract: false,
      implements: ['Timestamped'],
      attributes: ['createdAt', 'body'],
    },
    Identity: {
      abstract: true,
    },
  },

  edges: {
    follows: {
      endpoints: {
        follower: { types: ['User'] },
        followed: { types: ['User'] },
      },
      constraints: { no_self: true, unique: true },
      attributes: ['since'],
    },
    liked: {
      endpoints: {
        user: { types: ['User'] },
        post: { types: ['Post'] },
      },
      constraints: { unique: true },
    },
    authored: {
      endpoints: {
        author: { types: ['User'] },
        post: { types: ['Post'], cardinality: { min: 1, max: 1 } },
      },
    },
  },

  methods: {
    User: {
      followerCount: { params: {}, returns: 'Int' },
      isFollowing: { params: { other: { type: 'User' } }, returns: 'Boolean' },
    },
    Post: {
      likeCount: { params: {}, returns: 'Int' },
    },
  },
} as const

// ─── Bootstrap ──────────────────────────────────────────────

/** Bootstrap manifest — what class/interface nodes to create. */
export const schemaBootstrap = {
  classes: [
    { key: 'User', type: 'node' as const },
    { key: 'Post', type: 'node' as const },
    { key: 'follows', type: 'link' as const },
  ],
  interfaces: [
    { key: 'Timestamped' },
    { key: 'Identity' },
  ],
  implements: [
    { classKey: 'User', interfaceKey: 'Identity' },
    { classKey: 'User', interfaceKey: 'Timestamped' },
    { classKey: 'Post', interfaceKey: 'Timestamped' },
  ],
  extends: [
  ],
} as const

// ─── Method Factory ─────────────────────────────────────────

export const defineMethods = createMethodFactory<typeof schema, GeneratedTypeMap>()

export const defineUserMethods = defineMethods.withSelf<UserNode>()
export const definePostMethods = defineMethods.withSelf<PostNode>()

// ─── Schema Types ───────────────────────────────────────────

export type SchemaNodeType = 'User' | 'Post'
export type SchemaEdgeType = 'follows' | 'liked' | 'authored'
export type SchemaType = SchemaNodeType | SchemaEdgeType

// ─── Core ───────────────────────────────────────────────────

export interface CoreNodeProps {
  User: Partial<User>
  Post: Partial<Post>
}

export interface CoreEdgeEndpoints {
  follows: { follower: string; followed: string }
  liked: { user: string; post: string }
  authored: { author: string; post: string }
}

export interface CoreEdgeProps {
  follows: Partial<FollowsPayload>
}

export interface CoreNodeDef<T extends SchemaNodeType = SchemaNodeType> {
  readonly __type: T
  readonly props: CoreNodeProps[T]
  readonly children?: Record<string, CoreNodeDef>
}

export interface CoreEdgeDef<T extends SchemaEdgeType = SchemaEdgeType> {
  readonly __type: T
  readonly endpoints: CoreEdgeEndpoints[T]
  readonly props?: T extends keyof CoreEdgeProps ? CoreEdgeProps[T] : never
}

export interface CoreDefinition {
  nodes: Record<string, CoreNodeDef>
  edges?: CoreEdgeDef[]
}

export function node<T extends SchemaNodeType>(
  type: T,
  props: CoreNodeProps[T],
): CoreNodeDef<T>
export function node<T extends SchemaNodeType, C extends Record<string, CoreNodeDef>>(
  type: T,
  props: CoreNodeProps[T],
  children: C,
): CoreNodeDef<T> & { readonly children: C }
export function node(
  type: string,
  props: Record<string, unknown>,
  children?: Record<string, CoreNodeDef>,
): CoreNodeDef {
  return { __type: type as SchemaNodeType, props, ...(children ? { children } : {}) }
}

export function edge<T extends SchemaEdgeType>(
  type: T,
  endpoints: CoreEdgeEndpoints[T],
  props?: T extends keyof CoreEdgeProps ? CoreEdgeProps[T] : never,
): CoreEdgeDef<T> {
  return { __type: type, endpoints, ...(props ? { props } : {}) } as CoreEdgeDef<T>
}

export function defineCore<const T extends CoreDefinition>(def: T): T {
  return def
}

type FlattenCoreKeys<T extends Record<string, any>> =
  { [K in keyof T & string]: K | (T[K] extends { readonly children: infer C extends Record<string, any> } ? FlattenCoreKeys<C> : never) }[keyof T & string]

export type ExtractCoreKeys<T extends CoreDefinition> = FlattenCoreKeys<T['nodes']>

export type Refs<T extends CoreDefinition = CoreDefinition> =
  Record<SchemaType | Extract<ExtractCoreKeys<T>, string>, NodeId>

/** Nested core refs type - supports hierarchical access like core.electronics.phones */
type NestedCoreKeys<T extends Record<string, any>> = {
  [K in keyof T & string]: T[K] extends { readonly children: infer C extends Record<string, any> }
    ? NestedCoreKeys<C> & NodeId  // Parent with children
    : NodeId                       // Leaf node ID
}

export type CoreRefs<T extends CoreDefinition = CoreDefinition> =
  NestedCoreKeys<T['nodes']> & Record<SchemaType, NodeId>
